SHELL=/bin/sh

CFLAGS = -Wall -g
LDFLAGS= -lm
LOADLIBES=-lm

EXECUTABLES=	                   \
		exemple-atoi       \
		exemple-ecvt       \
		exemple-is         \
		exemple-isw        \
		exemple-towupper   \
		exemple-sizeof     \
		exemple-strtof     \
		exemple-strtol     \
		exemple-complexe   \
		exemple-arrondis   \
		exemple-infinis    \



all : ${EXECUTABLES}

clean : 
	@rm -f core* *.o *.out essai.* *~
	@rm -f ${EXECUTABLES}
