SHELL=/bin/sh

CFLAGS = -Wall -g

EXECUTABLES=	                      \
		exemple-buffers       \
		exemple-enum          \
		exemple-fopen         \
		exemple-freopen       \
		exemple-fseeko        \
		exemple-ftell         \
		exemple-fwrite        \
		taille-off-t          \


all : ${EXECUTABLES}

clean : 
	@rm -f core* *.o *.out essai.* *~
	@rm -f ${EXECUTABLES}
