SHELL=/bin/sh

CFLAGS = -Wall -g

EXECUTABLES=	exemple-mmap-1			\
		exemple-mmap-2			\
		exemple-mprotect-1		\
		exemple-mprotect-2		\


all : ${EXECUTABLES}

clean : 
	@rm -f core *.o *.out *~
	@rm -f ${EXECUTABLES}
