SHELL=/bin/sh

CFLAGS = -Wall -g

EXECUTABLES=                            \
		exemple-strsignal       \
		exemple-siginterrupt	\
		exemple-signal		\
		exemple-signal-2	\
		exemple-signal-3	\

all : ${EXECUTABLES}

clean : 
	@rm -f core *.o *.out *~
	@rm -f ${EXECUTABLES}
