SHELL=/bin/sh

CFLAGS = -Wall -g

EXECUTABLES=	exemple-fgetc       \
		exemple-fgets       \
		exemple-fprintf-1   \
		exemple-fprintf-2   \
		exemple-fprintf-3   \
		exemple-fprintf-4   \
		exemple-fprintf-5   \
		exemple-fputc       \
		exemple-fputs       \
		exemple-getchar     \
		exemple-getwchar    \
		exemple-getline     \
		exemple-puts        \
		exemple-scanf-1     \
		exemple-scanf-2     \
		exemple-scanf-3     \
		exemple-scanf-4     \
		exemple-scanf-5     \
		exemple-scanf-6     \
		exemple-scanf-7     \
		exemple-scanf-8     \
		exemple-ungetc      \
		exemple-vsnprintf   \


all : ${EXECUTABLES}

clean : 
	@rm -f core *.o *.out *~
	@rm -f ${EXECUTABLES}
