SHELL=/bin/sh

CFLAGS = -Wall -g

EXECUTABLES=	exemple-pipe-1		\
		exemple-pipe-2		\
		exemple-pipe-3		\
		exemple-pipe-4		\
		exemple-pipe-5		\
		exemple-pipe-6		\
		exemple-pipe-7		\
		exemple-pipe-8		\
		exemple-client		\
		exemple-serveur		\


all : ${EXECUTABLES}

clean : 
	@rm -f core* *.o *.out essai.* *~
	@rm -f ${EXECUTABLES}
