#! /bin/sh
# ------------------------------------------------------------------
# ls
# Fichier d'exemple du livre "Developpement Systeme sous Linux"
# (C) 2000-2011 - Christophe BLAESS -Christophe.Blaess@Logilin.fr
# http://www.logilin.fr
# ------------------------------------------------------------------


echo faux ls
echo qui lance un shell
sh

