#! /bin/sh
# ------------------------------------------------------------------
# ls
# Fichier d'exemple du livre "Developpement Systeme sous Linux"
# (C) 2000-2019 - Christophe BLAESS <christophe@blaess.fr>
# https://www.blaess.fr/christophe/
# ------------------------------------------------------------------


echo faux ls
echo qui lance un shell
sh

