CFLAGS = -Wall -g

EXEMPLES=                      \
	exemple-execve         \
	exemple-execvp         \
	exemple-execlp         \
	exemple-execv          \
	exemple-system         \
	exemple-popen-1        \
	exemple-popen-2        \
	exemple-popen-3        \

all : ${EXEMPLES}

clean : 
	@rm -f core *.o *.out *.bb *.bbg *.gcov *.da *~
	@rm -f ${EXEMPLES}

