SHELL=/bin/sh

CFLAGS = -Wall -g

EXECUTABLES=	exemple-hsearch		\
		exemple-hsearch-r	\
		exemple-qsort		\
		exemple-qsort-2		\
		exemple-tsearch		\


all : ${EXECUTABLES}

clean : 
	@rm -f core *.o *.out *~
	@rm -f ${EXECUTABLES}
