SHELL=/bin/sh

CFLAGS = -Wall -g -pthread

EXECUTABLES=                                 \
		exemple-pthread-cancel-1     \
		exemple-mutex-type-1         \
		exemple-mutex-type-2         \
		exemple-mutex-type-3         \
		exemple-mutex-type-4         \


all : ${EXECUTABLES}

clean : 
	@rm -f core *.o a.out *~
	@rm -f ${EXECUTABLES}
