SHELL=/bin/sh

CFLAGS = -Wall -g

EXECUTABLES=                            \
		exemple-fchdir		\
		exemple-fnmatch		\
		exemple-glob		\
		exemple-mkdir		\
		exemple-nftw		\
		exemple-opendir		\
		exemple-realpath	\
		exemple-scandir		\
		exemple-unlink		\
		exemple-wordexp		\


all : ${EXECUTABLES}

clean : 
	@rm -f core* *.o *.out essai.* *~
	@rm -f ${EXECUTABLES}
